pytorch:
  - EarlyStopping:
      mode: 'max'
      monitor: 'val_MulticlassAccuracy'
      patience: ${trainer.pytorch.global_train_params.patience}
      min_delta: 0.000001 # 1e-6
  - History
  - MetricMeter
  - ModelCheckpoint:
      mode: 'max'
      monitor: 'val_MulticlassAccuracy'

tensorflow:
  - History: null
  - MetricMeter: null
  - ModelCheckpoint: null
  - EarlyStopping: null
