defaults:
      - dataset: cifar10
      - resample: train_test_split
      - transform:
              - train
              - test
      - data_adapter:
              - adapter

module:
      _target_: src.data.data_module.ImageClassificationDataModule
      _recursive_: False

debug: ${debug}
num_debug_samples: 1000
