defaults:
      - data_set: common
      - resample: train_test_split
      - transform:
              - train
              - test
      - data_adapter:
              - pytorch

module:
      _target_: src.data_module.data_module.ImageClassificationDataModule
      _recursive_: False

debug: ${debug}
num_debug_samples: 1000
