defaults:
      - dataset: vegfru
      - resample: train_test_split
      - transform:
              - train
              - test
      - data_adapter:
              - adapter

module:
      _target_: src.data.data_module.ImageClassificationDataModule
      _recursive_: False

framework: ${framework}
debug: ${debug}
num_debug_samples: 300
