train:
  - _target_: torchvision.transforms.ToPILImage
  - _target_: torchvision.transforms.RandomResizedCrop
    image_size: (768, 768)
  - _target_: torchvision.transforms.ToTensor
  - _target_: torchvision.transforms.Normalize
    std: [0.229, 0.224, 0.225]
  