train:
  - _target_: torchvision.transforms.ToPILImage
  - _target_: torchvision.transforms.RandomResizedCrop
    size: 64
  - _target_: torchvision.transforms.ToTensor
  - _target_: torchvision.transforms.Normalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
