pytorch:
  adapter_type: "pytorch"
  scale: 1.

  train:
    batch_size: 32
    shuffle: True
    pin_memory: True
    drop_last: False

  valid:
    batch_size: 32
    shuffle: False
    pin_memory: True
    drop_last: False

  test:
    batch_size: 1
    shuffle: False
    pin_memory: True
    drop_last: False
tensorflow:
  adapter_type: "tensorflow"
  scale: 255.

  train:
    batch_size: 32
    shuffle: True
    x_col: ${data_module.dataset.image_path_col_name}
    y_col: ${data_module.dataset.target_col_name}
    target_size:
      - 32
      - 32
    color_mode: "rgb"
    classes: ${data_module.dataset.classes}
    class_mode: "categorical"
    interpolation: "nearest"
    subset: "training"

  valid:
    batch_size: 32
    shuffle: False
    x_col: ${data_module.dataset.image_path_col_name}
    y_col: ${data_module.dataset.target_col_name}
    target_size:
      - 32
      - 32
    color_mode: "rgb"
    classes: ${data_module.dataset.classes}
    class_mode: "categorical"
    interpolation: "nearest"
    subset: "validation"

  test:
    batch_size: 1
    shuffle: False
    x_col: ${data_module.dataset.image_path_col_name}
    y_col: ${data_module.dataset.target_col_name}
    target_size:
      - 32
      - 32
    color_mode: "rgb"
    classes: ${data_module.dataset.classes}
    class_mode: "categorical"
    interpolation: "nearest"
    subset: "validation"
