adapter_type: "tensorflow"
scale: 255.

train:
  batch_size: 32
  shuffle: True
  pin_memory: True
  drop_last: False

valid:
  batch_size: 32
  shuffle: True
  pin_memory: True
  drop_last: False

test:
  batch_size: 1
  shuffle: False
  pin_memory: True
  drop_last: False
