version: 1
disable_existing_loggers: False
formatters:
  json:
    format: "%(asctime)s %(process)d %(name)s %(levelname)s %(message)s"
    # class: pythonjsonlogger.jsonlogger.JsonFormatter
    datefmt: "%Y%m%d_%H%M%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: json

  debug_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: json
      filename: "${hydra.run.dir}/debug.log"
      maxBytes: 10485760 # 10MB
      backupCount: 20
      encoding: utf8
      delay: True

  info_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: json
      filename: "${hydra.run.dir}/info.log"
      maxBytes: 10485760 # 10MB
      backupCount: 20
      encoding: utf8
      delay: True

  error_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: ERROR
      formatter: json
      filename: "${hydra.run.dir}/errors.log"
      maxBytes: 10485760 # 10MB
      backupCount: 20
      encoding: utf8
      delay: True

root:
  level: INFO
  handlers: [console, debug_file_handler, info_file_handler, error_file_handler]
