input: ["img", "masks", "bbox_labels"]
output: ["img"]

instance_color_scheme: hue_family
effect: {
  contrast: null,
  brightness: null,
  gamma_correction: null,
  blur: null,
  mosaic: null
}
effect_area: objects
contours: {
    show: False,
    thickness: 2
}
