project_name: "myproject"  # To be configured for each experiment

defaults:
  - use_case: detection  # classification | detection

  # Do NOT change the following
  - data_module: ${use_case}
  - model: ${use_case}
  - trainer: ${use_case}
  - callbacks: ${use_case}
  - metrics: ${use_case}
  - model_analysis: ${use_case}
  - stores: ${use_case}
  - _self_
  - override hydra/job_logging: custom

hydra:
  run:
    dir: "outputs/${project_name}/${stores.unique_id}"
  sweep:
    dir: outputs/${project_name}/${stores.unique_id}
    subdir: ${hydra.job.num}
