defaults:
  # - base_config
  - data_module: common
  - model: common
  - trainer: common
  - callbacks: common
  - metrics: common
  - stores: common
  # You typically want _self_ somewhere after the schema (base_config)
  - _self_
  - override hydra/job_logging: custom

device: "cpu"
project_name: "CIFAR-10"
debug: True


hydra:
  run:
    dir: "outputs/${project_name}/${stores.unique_id}"
