device: "auto"
project_name: "cifar10" #rsna | cifar10 | vegfru
debug: True
framework: "pytorch" # 'pytorch' | 'tensorflow'

defaults:
  - use_case: classification # classification | detection | segmentation
  - data_module: cifar10 #rsna | cifar10 | vegfru
  - model: ${use_case}
  - trainer: ${use_case}
  - callbacks: ${use_case}
  - metrics: ${use_case}
  - model_analysis: ${use_case}
  - stores: ${use_case}
  - _self_
  - override hydra/job_logging: custom

hydra:
  run:
    dir: "outputs/${project_name}/${stores.unique_id}"
