device: "auto" # "auto" to select available gpu. "cpu"|"cuda"|"mps"
project_name: "yolox_integration" #rsna | cifar10 | vegfru | vegfru5 | vegfru20
debug: True
framework: "pytorch" # 'pytorch' | 'tensorflow'
random_state: 11
view_only: False
pipeline: "detection" # classification | detection | segmentation

defaults:
  - use_case: detection # classification | detection | segmentation
  - data_module: detection # rsna | cifar10 | vegfru | vegfru5 | vegfru20 | detection
  - model: ${use_case}
  - trainer: ${use_case}
  - callbacks: ${use_case}
  - metrics: ${use_case}
  - model_analysis: ${use_case}
  - stores: ${use_case}
  - _self_
  - override hydra/job_logging: custom

hydra:
  run:
    dir: "outputs/${project_name}/${stores.unique_id}"
  sweep:
    dir: outputs/${project_name}/${stores.unique_id}
    subdir: ${hydra.job.num}
