defaults:
  - use_case: common
  - data_module: ${use_case}
  - model: ${use_case}
  - trainer: ${use_case}
  - callbacks: ${use_case}
  - metrics: ${use_case}
  - stores: ${use_case}
  - _self_
  - override hydra/job_logging: custom

device: "cpu"
project_name: "CIFAR-10"
debug: True
framework: "pytorch" # 'pytorch' | 'tensorflow'

hydra:
  run:
    dir: "outputs/${project_name}/${stores.unique_id}"
