device: "auto"  # "auto" to select available gpu. "cpu"|"cuda"|"mps"
project_name: "cifar10" #rsna | cifar10 | vegfru | vegfru5 | vegfru20
debug: True
framework: "tensorflow" # 'pytorch' | 'tensorflow'
random_state: 11

defaults:
  - use_case: classification # classification | detection | segmentation
  - data_module: cifar10 #rsna | cifar10 | vegfru | vegfru5 | vegfru20
  - model: ${use_case}
  - trainer: ${use_case}
  - callbacks: ${use_case}
  - metrics: ${use_case}
  - model_analysis: ${use_case}
  - stores: ${use_case}
  - _self_
  - override hydra/job_logging: custom

hydra:
  run:
    dir: "outputs/${project_name}/${stores.unique_id}"
  sweep:
    dir: outputs/${project_name}/${stores.unique_id}
    subdir: ${hydra.job.num}
