pytorch:
    global_train_params:
        manual_seed: ${random_state}
        epochs: 10
        patience: 3
        model_name: ${model.pytorch.model_name}
        debug: ${debug}
        debug_epochs: 3
        classification_type: ${data_module.dataset.classification_type}
        monitored_metric:
            monitor: val_MulticlassAccuracy
            mode: max
        trainer:
            _target_: src.trainer.pytorch_trainer.PytorchTrainer
    optimizer_params:
        optimizer: "Adam"
        optimizer_params:
            lr: 1e-5
            betas: [0.9, 0.999]
            amsgrad: False
            eps: 0.0000007
        finetune_params:
            lr: 1e-5
    scheduler_params:
        scheduler: null
        scheduler_params: null
    criterion_params:
        train_criterion: "CrossEntropyLoss"
        train_criterion_params:
            weight: null
            size_average: null
            ignore_index: -100
            reduce: null
            reduction: "mean"
            label_smoothing: 0.0
        valid_criterion: "CrossEntropyLoss"
        valid_criterion_params:
            weight: null
            size_average: null
            ignore_index: -100
            reduce: null
            reduction: "mean"
            label_smoothing: 0.0
    stores:
        project_name: ${project_name}
        unique_id: ${stores.unique_id} # field(default_factory=generate_uuid4)
        model_artifacts_dir: "./outputs/${project_name}/${stores.unique_id}/"


tensorflow:
    global_train_params:
        manual_seed: ${random_state}
        epochs: 10
        debug: ${debug}
        debug_epochs: 3
        trainer:
            _target_: src.trainer.tensorflow_trainer.TensorflowTrainer
    optimizer_params:
        optimizer: "Adam"
        optimizer_params:
            beta_1: 0.9
            beta_2: 0.999
            epsilon: 0.0000007
            name: "Adam"
        finetune_learning_rate: 1e-5
    lr_schedule_params:
        schedule: null
        schedule_params:
            learning_rate: 1e-5
    loss_params:
        loss_func: "CategoricalCrossentropy"
        loss_params:
            from_logits: False