adapter: "torchvision"
model_type: "classification"
model_name: "resnet18"
num_classes: ${data_module.data_set.num_classes}
device: ${device}
pretrained: True
# You typically want _self_ somewhere after the schema (base_config)