download: False
url: "https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz"
blob_file: "cifar10.zip"
root_dir: "data"
train_dir: "./${.root_dir}/${project_name}"
test_dir: "./${.root_dir}/${project_name}"
train_csv: "./${.root_dir}/${project_name}/train.csv"
image_path_col_name: "image_path"
target_col_name: "class_id"
stratify_by: "${.target_col_name}"
classification_type: "multiclass"
num_classes: 10
class_name_to_id:
  airplane: 0
  automobile: 1
  bird: 2
  cat: 3
  deer: 4
  dog: 5
  frog: 6
  horse: 7
  ship: 8
  truck: 9
