download: False
url: ""
blob_file: "vegfru.zip"
root_dir: "data"
train_dir: "./${.root_dir}/vegfru"
test_dir: "./${.root_dir}/vegfru"
train_csv: "./${.root_dir}/vegfru/train.csv"
image_path_col_name: "image_path"
target_col_name: "class_name"
target_col_id: "class_id"
stratify_by: "class_name"
classification_type: "multiclass"
image_size: 224
num_classes: 25
class_name_to_id:
  "alliaceous": 0
  "aquatic_vegetable": 1
  "beans": 2
  "brassia_olreacea": 3
  "bug_seedling": 4
  "cabbage": 5
  "eggplant": 6
  "green_leafy_vegatable": 7
  "melon": 8
  "mushroom": 9
  "mustard": 10
  "perennial": 11
  "root_vegetable": 12
  "tuber_vagetable": 13
  "wild_vegetable": 14
  "berry_fruit": 15
  "citrus_fruit": 16
  "collective_fruit": 17
  "cucurbites": 18
  "drupe": 19
  "litchies": 20
  "nut_fruit": 21
  "persimmons_and_jujubes_fruit": 22
  "pome": 23
  "other_fruit": 24
